In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Walmart.csv')
df.head(5)

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [3]:
df.shape

(10051, 11)

In [4]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [5]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [7]:
df.duplicated().sum()

np.int64(51)

In [8]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [12]:
# df['unit_price']=df['unit_price'].astype('float')
df['unit_price']=df['unit_price'].str.replace('$','')
df['unit_price']=df['unit_price'].astype(float)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [ ]:
# Find the total sales revenue (unit_price * quantity).
df['total']=df['unit_price']*df['quantity']

In [18]:
import pandas as pd
from sqlalchemy import create_engine
import os

conn_string = "mysql+mysqlconnector://root:patricks114@localhost:3306/walmart"
db = create_engine(conn_string)
conn = db.connect()

folder_path = r"F:\jupyter files\walmart_sales"

for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        table_name = os.path.splitext(file)[0]  
        file_path = os.path.join(folder_path, file)

        df = pd.read_csv(file_path)

        df.to_sql(table_name, con=conn, if_exists='replace', index=False)

        print(f"{file} uploaded successfully into table '{table_name}'")

Walmart.csv uploaded successfully into table 'Walmart'

C:\Users\hp\AppData\Local\Temp\ipykernel_19728\3511981056.py:18: UserWarning: The provided table name 'Walmart' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  df.to_sql(table_name, con=conn, if_exists='replace', index=False)

In [81]:

# Calculate the total quantity of items sold.
# quantity=df['quantity'].sum()
# quantity


# Find the average unit_price across all transactions.
# avg_price=df['unit_price'].mean().round(2)
# avg_price


# Count how many unique product categories exist.

# it igves total unique count of products
# unique_product=df['category'].nunique()
# unique_product

# it gives the unique product list
# unique_product=df['category'].unique()
# print(sorted(unique_product))


# Find the most common payment_method.
# payment_method = (
#     df.groupby('payment_method')['invoice_id']
#       .count()
#       .reset_index()
#       .rename(columns={'invoice_id': 'total_transactions'})
#       .sort_values(by='total_transactions', ascending=False)
# )

# print(payment_method.head(1)) 


# Show the total sales per Branch.
# sales_per_branch=df.groupby('Branch')['total'].sum().round(2).reset_index().rename(columns={'total':'total_sales'}).sort_values(by='Branch')
# sales_per_branch


# Find the highest rating given by a customer.
# maxi_rating=df['rating'].max()
# maxi_rating


# Show the average profit_margin across all sales.
# avg_profit_margin=df['profit_margin'].mean().round(2)
# avg_profit_margin


# Convert date to datetime and extract the day of the week each transaction occurred.
# 1️⃣ First convert date & time separately to datetime64[ns]
# df['date'] = pd.to_datetime(df['date'], errors='coerce')


# # 2️⃣ If you want a full datetime column (recommended for time-series)
# df['datetime'] = pd.to_datetime(df['date'].astype(str) + ' ' + df['time'].astype(str))

# df.info()



# 🔹 Medium (Business Insights)

# Calculate the total revenue per product category.
# category_revenue=df.groupby('category')['total'].sum().reset_index().rename(columns={'total':'total_revenue'})
# category_revenue


# Find which city generated the highest sales revenue.
# city_revenue=df.groupby('City')['total'].sum().reset_index().rename(columns={'total':'total_revenue'})
# city_revenue


# Compare the sales distribution by payment method (e.g., cash vs card).
# payment_method_sales=df.groupby('payment_method')['total'].sum().reset_index().rename(columns={'total':'total_sales'})
# payment_method_sales


# Find the average basket size (avg quantity per invoice).
# avg_quantity=df.groupby('category')['quantity'].mean().round(0).reset_index().rename(columns={'quantity':"avg_quantity"})
# avg_quantity


# Calculate the monthly sales trend (group by month).
# adding the month and year columns in the dataframe
# df['month']=df['date'].dt.month
# df['year']=df['date'].dt.year

# monthly_sales=df.groupby('month')['total'].sum().reset_index().rename(columns={'total':'monthly_sales'}).sort_values(by='monthly_sales',ascending=False)
# monthly_sales



# Find the most profitable category based on profit_margin.

# profit = df.groupby('category').agg(
#     total_revenue=('total', 'sum'),
#     total_profit_margin=('profit_margin', 'sum')
# ).reset_index().sort_values(by='total_profit_margin',ascending=False)

# print(profit)



# Calculate the average rating per branch.
# branch_avg_rating=df.groupby('Branch')['rating'].mean().round(0).reset_index().rename(columns={'rating':'avg_rating'})
# branch_avg_rating


# Identify the branch with the highest average profit margin.
# avg_profit_margin=df.groupby('Branch')['profit_margin'].mean().round(2).reset_index().rename(columns={'profit_margin':'avg_profit_margin'}).sort_values(by='avg_profit_margin',ascending=False)
# avg_profit_margin.head(3)


# Find the peak sales hour of the day from the time column.
# df['hour']=df['datetime'].dt.hour
# peak_sales=df.groupby('hour')['total'].sum().round(2).reset_index().rename(columns={'total':'total_sales'}).sort_values(by='total_sales',ascending=False)
# peak_sales


# Identify the top 3 performing branches each month by revenue.
# sales_per_month=df.groupby(['Branch','month'])['total'].sum().reset_index().rename(columns={'total':'total_sales'})
# sales_per_month['rank']=sales_per_month.groupby('month')['total_sales'].rank(method='dense',ascending=False)
# top_3_branch=sales_per_month[sales_per_month['rank']<=3]
# top_3_branch


# Calculate average profit per transaction by payment method.
# avg_profit=df.groupby('payment_method')['profit_margin'].mean().round(2).reset_index().rename({'profit_margin':'avg_profit_margin'})
# avg_profit


# Compute the profit contribution % of each category relative to total profit.

# df['profit'] = df['total'] * df['profit_margin']

# category_profit = (
#     df.groupby('category')['profit']
#       .sum()
#       .reset_index()
#       .rename(columns={'profit':'cat_profit'})
# )

# total_profit = category_profit['cat_profit'].sum()

# category_profit['contribution'] = (category_profit['cat_profit'] / total_profit * 100).round(2)

# print(category_profit.sort_values(by='contribution',ascending=False))




# Segment sales into time slots (Morning, Afternoon, Evening, Night) and find which slot performs best.
# import numpy as np
# conditions=[df['hour']<12,df['hour'].between(12,16)]
# result=['Morning','Afternoon']
# df['shift']=np.select(conditions,result,default='Evening')

# shift_sales = (
#     df.groupby('shift', as_index=False)['total']
#       .sum()
#       .rename(columns={'total': 'total_sales'})
#       .sort_values(by='total_sales', ascending=False)
# )
# shift_sales


# Predict future sales trends using a time-series forecast (e.g., ARIMA/Prophet in Python).

# rolling 7 day average sales revenue
rolling_average=df.groupby('date')['total'].sum().reset_index()
rolling_average['7d_avg']=rolling_average['total'].rolling(window=7).mean().round(2)
rolling_average.head(15)

         date    total   7d_avg
0  2019-01-01  4519.22      NaN
1  2019-01-02  2328.13      NaN
2  2019-01-03  2508.92      NaN
3  2019-01-13  2334.48      NaN
4  2019-01-14  3777.73      NaN
5  2019-01-15  5661.20      NaN
6  2019-01-16  4084.84  3602.07
7  2019-01-17  2993.10  3384.06
8  2019-01-18  2648.07  3429.76
9  2019-01-19  4680.69  3740.02
10 2019-01-20  3481.38  3903.86
11 2019-01-21  2278.19  3689.64
12 2019-01-22  1623.59  3112.84
13 2019-01-23  5708.75  3344.82
14 2019-01-24  5144.81  3652.21